apiVersion: sources.eventing.knative.dev/v1alpha1
kind: GitHubSource
metadata:
  namespace: tekton-dream
  name: demo-event-source
spec:
  eventTypes:
    - pull_request
  ownerAndRepository: mmitrasarkar/expense-share-app
  accessToken:
    secretKeyRef:
      name: githubsecret
      key: accessToken
  secretToken:
    secretKeyRef:
      name: githubsecret
      key: secretToken
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Broker
    name: ci-builds
    namespace: tekton-dream
